const kanjiData = {　
    hiragana: [
        { kanji: "あ", readings: ["a"], meanings: ["あ", "ア", "a"] },
        { kanji: "い", readings: ["i"], meanings: ["い", "イ", "i"] },
        { kanji: "う", readings: ["u"], meanings: ["う", "ウ", "u"] },
        { kanji: "え", readings: ["e"], meanings: ["え", "エ", "e"] },
        { kanji: "お", readings: ["o"], meanings: ["お", "オ", "o"] },
        { kanji: "か", readings: ["ka"], meanings: ["か", "カ", "ka"] },
        { kanji: "き", readings: ["ki"], meanings: ["き", "キ", "ki"] },
        { kanji: "く", readings: ["ku"], meanings: ["く", "ク", "ku"] },
        { kanji: "け", readings: ["ke"], meanings: ["け", "ケ", "ke"] },
        { kanji: "こ", readings: ["ko"], meanings: ["こ", "コ", "ko"] },
        { kanji: "さ", readings: ["sa"], meanings: ["さ", "サ", "sa"] },
        { kanji: "し", readings: ["shi"], meanings: ["し", "シ", "shi"] },
        { kanji: "す", readings: ["su"], meanings: ["す", "ス", "su"] },
        { kanji: "せ", readings: ["se"], meanings: ["せ", "セ", "se"] },
        { kanji: "そ", readings: ["so"], meanings: ["そ", "ソ", "so"] },
        { kanji: "た", readings: ["ta"], meanings: ["た", "タ", "ta"] },
        { kanji: "ち", readings: ["chi"], meanings: ["ち", "チ", "chi"] },
        { kanji: "つ", readings: ["tsu"], meanings: ["つ", "ツ", "tsu"] },
        { kanji: "て", readings: ["te"], meanings: ["て", "テ", "te"] },
        { kanji: "と", readings: ["to"], meanings: ["と", "ト", "to"] },
        { kanji: "な", readings: ["na"], meanings: ["な", "ナ", "na"] },
        { kanji: "に", readings: ["ni"], meanings: ["に", "ニ", "ni"] },
        { kanji: "ぬ", readings: ["nu"], meanings: ["ぬ", "ヌ", "nu"] },
        { kanji: "ね", readings: ["ne"], meanings: ["ね", "ネ", "ne"] },
        { kanji: "の", readings: ["no"], meanings: ["の", "ノ", "no"] },
        { kanji: "は", readings: ["ha"], meanings: ["は", "ハ", "ha"] },
        { kanji: "ひ", readings: ["hi"], meanings: ["ひ", "ヒ", "hi"] },
        { kanji: "ふ", readings: ["fu"], meanings: ["ふ", "フ", "fu"] },
        { kanji: "へ", readings: ["he"], meanings: ["へ", "ヘ", "he"] },
        { kanji: "ほ", readings: ["ho"], meanings: ["ほ", "ホ", "ho"] },
        { kanji: "ま", readings: ["ma"], meanings: ["ま", "マ", "ma"] },
        { kanji: "み", readings: ["mi"], meanings: ["み", "ミ", "mi"] },
        { kanji: "む", readings: ["mu"], meanings: ["む", "ム", "mu"] },
        { kanji: "め", readings: ["me"], meanings: ["め", "メ", "me"] },
        { kanji: "も", readings: ["mo"], meanings: ["も", "モ", "mo"] },
        { kanji: "や", readings: ["ya"], meanings: ["や", "ヤ", "ya"] },
        { kanji: "ゆ", readings: ["yu"], meanings: ["ゆ", "ユ", "yu"] },
        { kanji: "よ", readings: ["yo"], meanings: ["よ", "ヨ", "yo"] },
        { kanji: "ら", readings: ["ra"], meanings: ["ら", "ラ", "ra"] },
        { kanji: "り", readings: ["ri"], meanings: ["り", "リ", "ri"] },
        { kanji: "る", readings: ["ru"], meanings: ["る", "ル", "ru"] },
        { kanji: "れ", readings: ["re"], meanings: ["れ", "レ", "re"] },
        { kanji: "ろ", readings: ["ro"], meanings: ["ろ", "ロ", "ro"] },
        { kanji: "わ", readings: ["wa"], meanings: ["わ", "ワ", "wa"] },
        { kanji: "を", readings: ["wo"], meanings: ["を", "ヲ", "wo", "o"] },
        { kanji: "ん", readings: ["n"], meanings: ["ん", "ン", "n"] }
    ],
    katakana: [
        { kanji: "ア", readings: ["a"], meanings: ["あ", "ア", "a"] },
        { kanji: "イ", readings: ["i"], meanings: ["い", "イ", "i"] },
        { kanji: "ウ", readings: ["u"], meanings: ["う", "ウ", "u"] },
        { kanji: "エ", readings: ["e"], meanings: ["え", "エ", "e"] },
        { kanji: "オ", readings: ["o"], meanings: ["お", "オ", "o"] },
        { kanji: "カ", readings: ["ka"], meanings: ["か", "カ", "ka"] },
        { kanji: "キ", readings: ["ki"], meanings: ["き", "キ", "ki"] },
        { kanji: "ク", readings: ["ku"], meanings: ["く", "ク", "ku"] },
        { kanji: "ケ", readings: ["ke"], meanings: ["け", "ケ", "ke"] },
        { kanji: "コ", readings: ["ko"], meanings: ["こ", "コ", "ko"] },
        { kanji: "サ", readings: ["sa"], meanings: ["さ", "サ", "sa"] },
        { kanji: "シ", readings: ["shi"], meanings: ["し", "シ", "shi"] },
        { kanji: "ス", readings: ["su"], meanings: ["す", "ス", "su"] },
        { kanji: "セ", readings: ["se"], meanings: ["せ", "セ", "se"] },
        { kanji: "ソ", readings: ["so"], meanings: ["そ", "ソ", "so"] },
        { kanji: "タ", readings: ["ta"], meanings: ["た", "タ", "ta"] },
        { kanji: "チ", readings: ["chi"], meanings: ["ち", "チ", "chi"] },
        { kanji: "ツ", readings: ["tsu"], meanings: ["つ", "ツ", "tsu"] },
        { kanji: "テ", readings: ["te"], meanings: ["て", "テ", "te"] },
        { kanji: "ト", readings: ["to"], meanings: ["と", "ト", "to"] },
        { kanji: "ナ", readings: ["na"], meanings: ["な", "ナ", "na"] },
        { kanji: "ニ", readings: ["ni"], meanings: ["に", "ニ", "ni"] },
        { kanji: "ヌ", readings: ["nu"], meanings: ["ぬ", "ヌ", "nu"] },
        { kanji: "ネ", readings: ["ne"], meanings: ["ね", "ネ", "ne"] },
        { kanji: "ノ", readings: ["no"], meanings: ["の", "ノ", "no"] },
        { kanji: "ハ", readings: ["ha"], meanings: ["は", "ハ", "ha"] },
        { kanji: "ヒ", readings: ["hi"], meanings: ["ひ", "ヒ", "hi"] },
        { kanji: "フ", readings: ["fu"], meanings: ["ふ", "フ", "fu"] },
        { kanji: "ヘ", readings: ["he"], meanings: ["へ", "ヘ", "he"] },
        { kanji: "ホ", readings: ["ho"], meanings: ["ほ", "ホ", "ho"] },
        { kanji: "マ", readings: ["ma"], meanings: ["ま", "マ", "ma"] },
        { kanji: "ミ", readings: ["mi"], meanings: ["み", "ミ", "mi"] },
        { kanji: "ム", readings: ["mu"], meanings: ["む", "ム", "mu"] },
        { kanji: "メ", readings: ["me"], meanings: ["め", "メ", "me"] },
        { kanji: "モ", readings: ["mo"], meanings: ["も", "モ", "mo"] },
        { kanji: "ヤ", readings: ["ya"], meanings: ["や", "ヤ", "ya"] },
        { kanji: "ユ", readings: ["yu"], meanings: ["ゆ", "ユ", "yu"] },
        { kanji: "ヨ", readings: ["yo"], meanings: ["よ", "ヨ", "yo"] },
        { kanji: "ラ", readings: ["ra"], meanings: ["ら", "ラ", "ra"] },
        { kanji: "リ", readings: ["ri"], meanings: ["り", "リ", "ri"] },
        { kanji: "ル", readings: ["ru"], meanings: ["る", "ル", "ru"] },
        { kanji: "レ", readings: ["re"], meanings: ["れ", "レ", "re"] },
        { kanji: "ロ", readings: ["ro"], meanings: ["ろ", "ロ", "ro"] },
        { kanji: "ワ", readings: ["wa"], meanings: ["わ", "ワ", "wa"] },
        { kanji: "ヲ", readings: ["wo"], meanings: ["を", "ヲ", "wo"] },
        { kanji: "ン", readings: ["n"], meanings: ["ん", "ン", "n"] }
    ],
    exthiragana: [
        { kanji: "が", readings: ["ga"], meanings: ["が", "ガ", "ga", "voiced ka"] },
        { kanji: "ぎ", readings: ["gi"], meanings: ["ぎ", "ギ", "gi", "voiced ki"] },
        { kanji: "ぐ", readings: ["gu"], meanings: ["ぐ", "グ", "gu", "voiced ku"] },
        { kanji: "げ", readings: ["ge"], meanings: ["げ", "ゲ", "ge", "voiced ke"] },
        { kanji: "ご", readings: ["go"], meanings: ["ご", "ゴ", "go", "voiced ko"] },
        { kanji: "ざ", readings: ["za"], meanings: ["ざ", "ザ", "za", "voiced sa"] },
        { kanji: "じ", readings: ["ji"], meanings: ["じ", "ジ", "ji", "voiced shi"] },
        { kanji: "ず", readings: ["zu"], meanings: ["ず", "ズ", "zu", "voiced su"] },
        { kanji: "ぜ", readings: ["ze"], meanings: ["ぜ", "ゼ", "ze", "voiced se"] },
        { kanji: "ぞ", readings: ["zo"], meanings: ["ぞ", "ゾ", "zo", "voiced so"] },
        { kanji: "だ", readings: ["da"], meanings: ["だ", "ダ", "da", "voiced ta"] },
        { kanji: "ぢ", readings: ["ji"], meanings: ["ぢ", "ヂ", "ji", "voiced chi"] },
        { kanji: "づ", readings: ["zu"], meanings: ["づ", "ヅ", "zu", "voiced tsu"] },
        { kanji: "で", readings: ["de"], meanings: ["で", "デ", "de", "voiced te"] },
        { kanji: "ど", readings: ["do"], meanings: ["ど", "ド", "do", "voiced to"] },
        { kanji: "ば", readings: ["ba"], meanings: ["ば", "バ", "ba", "voiced ha"] },
        { kanji: "び", readings: ["bi"], meanings: ["び", "ビ", "bi", "voiced hi"] },
        { kanji: "ぶ", readings: ["bu"], meanings: ["ぶ", "ブ", "bu", "voiced fu"] },
        { kanji: "べ", readings: ["be"], meanings: ["べ", "ベ", "be", "voiced he"] },
        { kanji: "ぼ", readings: ["bo"], meanings: ["ぼ", "ボ", "bo", "voiced ho"] },
        { kanji: "ぱ", readings: ["pa"], meanings: ["ぱ", "パ", "pa", "ha with handakuten"] },
        { kanji: "ぴ", readings: ["pi"], meanings: ["ぴ", "ピ", "pi", "hi with handakuten"] },
        { kanji: "ぷ", readings: ["pu"], meanings: ["ぷ", "プ", "pu", "fu with handakuten"] },
        { kanji: "ぺ", readings: ["pe"], meanings: ["ぺ", "ペ", "pe", "he with handakuten"] },
        { kanji: "ぽ", readings: ["po"], meanings: ["ぽ", "ポ", "po", "ho with handakuten"] },
        { kanji: "ゃ", readings: ["ya"], meanings: ["ゃ", "ャ", "ya", "small ya"] },
        { kanji: "ゅ", readings: ["yu"], meanings: ["ゅ", "ュ", "yu", "small yu"] },
        { kanji: "ょ", readings: ["yo"], meanings: ["ょ", "ョ", "yo", "small yo"] }
    ],
    extkatakana: [
        { kanji: "ガ", readings: ["ga"], meanings: ["が", "ガ", "ga", "voiced ka"] },
        { kanji: "ギ", readings: ["gi"], meanings: ["ぎ", "ギ", "gi", "voiced ki"] },
        { kanji: "グ", readings: ["gu"], meanings: ["ぐ", "グ", "gu", "voiced ku"] },
        { kanji: "ゲ", readings: ["ge"], meanings: ["げ", "ゲ", "ge", "voiced ke"] },
        { kanji: "ゴ", readings: ["go"], meanings: ["ご", "ゴ", "go", "voiced ko"] },
        { kanji: "ザ", readings: ["za"], meanings: ["ざ", "ザ", "za", "voiced sa"] },
        { kanji: "ジ", readings: ["ji"], meanings: ["じ", "ジ", "ji", "voiced shi"] },
        { kanji: "ズ", readings: ["zu"], meanings: ["ず", "ズ", "zu", "voiced su"] },
        { kanji: "ゼ", readings: ["ze"], meanings: ["ぜ", "ゼ", "ze", "voiced se"] },
        { kanji: "ゾ", readings: ["zo"], meanings: ["ぞ", "ゾ", "zo", "voiced so"] },
        { kanji: "ダ", readings: ["da"], meanings: ["だ", "ダ", "da", "voiced ta"] },
        { kanji: "ヂ", readings: ["ji"], meanings: ["ぢ", "ヂ", "ji", "voiced chi"] },
        { kanji: "ヅ", readings: ["zu"], meanings: ["づ", "ヅ", "zu", "voiced tsu"] },
        { kanji: "デ", readings: ["de"], meanings: ["で", "デ", "de", "voiced te"] },
        { kanji: "ド", readings: ["do"], meanings: ["ど", "ド", "do", "voiced to"] },
        { kanji: "バ", readings: ["ba"], meanings: ["ば", "バ", "ba", "voiced ha"] },
        { kanji: "ビ", readings: ["bi"], meanings: ["び", "ビ", "bi", "voiced hi"] },
        { kanji: "ブ", readings: ["bu"], meanings: ["ぶ", "ブ", "bu", "voiced fu"] },
        { kanji: "ベ", readings: ["be"], meanings: ["べ", "ベ", "be", "voiced he"] },
        { kanji: "ボ", readings: ["bo"], meanings: ["ぼ", "ボ", "bo", "voiced ho"] },
        { kanji: "パ", readings: ["pa"], meanings: ["ぱ", "パ", "pa", "ha with handakuten"] },
        { kanji: "ピ", readings: ["pi"], meanings: ["ぴ", "ピ", "pi", "hi with handakuten"] },
        { kanji: "プ", readings: ["pu"], meanings: ["ぷ", "プ", "pu", "fu with handakuten"] },
        { kanji: "ペ", readings: ["pe"], meanings: ["ぺ", "ペ", "pe", "he with handakuten"] },
        { kanji: "ポ", readings: ["po"], meanings: ["ぽ", "ポ", "po", "ho with handakuten"] },
        { kanji: "ャ", readings: ["ya"], meanings: ["ゃ", "ャ", "ya", "small ya"] },
        { kanji: "ュ", readings: ["yu"], meanings: ["ゅ", "ュ", "yu", "small yu"] },
        { kanji: "ョ", readings: ["yo"], meanings: ["ょ", "ョ", "yo", "small yo"] }
    ],
    Everything: []
};

kanjiData.Everything = [
    ...kanjiData.hiragana,
    ...kanjiData.katakana,
    ...kanjiData.exthiragana,
    ...kanjiData.extkatakana
];